package Kode;
import javax.swing.JOptionPane;

/**
 *
 * @author SIKESDU Developer
 */
public class BMI_Frame extends javax.swing.JFrame {

    public BMI_Frame() {
        initComponents();
        kosong();
    }
    
    //Deklarasi variabel global
    double hasilBMI, berat, tinggi;
    int usia;
    String kategori[] = {"SANGAT KURUS", "KURUS", "IDEAL", "GEMUK", "OBESITAS"};
    
    //Fungsi Hapus isi Kolom
    private void kosong(){
        txt_nama.setText("");
        txt_usia.setText("");
        txt_berat.setText("");
        txt_tinggi.setText("");
        combo_jk.setSelectedIndex(0);
        lbl_captNama.setText("");
        lbl_captNama.setVisible(false);
        lbl_captBMI.setText("");
        lbl_captBMI.setVisible(false);
        lbl_captKategori.setText("");
        lbl_captKategori.setVisible(false);
        lbl_capt1.setVisible(false);
        lbl_capt2.setVisible(false);
        lbl_capt3.setVisible(false);
        lbl_capt4.setVisible(false);
        lbl_capt5.setVisible(false);
        lbl_capt6.setVisible(false);
        lbl_capt7.setVisible(false);
    }
    
    //Fungsi Hitung BMI
    private void hitungBMI(){
        if(usia >= 18){
            hasilBMI = (berat / ((tinggi/100)*(tinggi/100)));
            lbl_captBMI.setText(String.format("%.2f",hasilBMI));
            if(hasilBMI < 17.0){
                lbl_captKategori.setText(kategori[0]);
            }else if(hasilBMI >= 17.0 && hasilBMI < 18.5){
                lbl_captKategori.setText(kategori[1]);
            }else if(hasilBMI >= 18.5 && hasilBMI < 25.0){
                lbl_captKategori.setText(kategori[2]);
            }else if(hasilBMI >= 25.0 && hasilBMI < 27.0){
                lbl_captKategori.setText(kategori[3]);
            }else if(hasilBMI >= 27.0){
                lbl_captKategori.setText(kategori[4]);
            }
            cetakHasil();
        }else{
            JOptionPane.showMessageDialog(this, "Usia dibawah 18 Tahun!");
        }   
    }
    
    //Fungsi cek Inputan
    private void cekInput(){
        try{
            if(txt_nama.getText().equals("") || 
               txt_usia.getText().equals("") || 
               txt_tinggi.getText().equals("") || 
               txt_berat.getText().equals("") || 
               combo_jk.getSelectedItem().equals("PILIH")){
                JOptionPane.showMessageDialog(this, "Seluruh kolom harus di isi!");
            }else{
                usia = Integer.parseInt(txt_usia.getText());
                tinggi = Double.parseDouble(txt_tinggi.getText());
                berat = Double.parseDouble(txt_berat.getText());
                if(usia <= 0 || tinggi <= 0.0 || berat <= 0.0){
                    JOptionPane.showMessageDialog(null, "Inputan Tidak Valid!!!");
                }else if(usia < 18){
                    JOptionPane.showMessageDialog(null, "Perhitungan BMI hanya untuk "
                                                                   + "\nUsia 18 Tahun Keatas");
                }else{
                    hitungBMI();
                }
            }
        }catch(Exception E){
            JOptionPane.showMessageDialog(null, "Inputan Tidak Valid!!!");
        }
    }
    
    //Fungsi tampilkan hasil
    private void cetakHasil(){
        lbl_captNama.setText(txt_nama.getText());
        lbl_captNama.setVisible(true);
        lbl_captBMI.setVisible(true);
        lbl_captKategori.setVisible(true);
        lbl_capt1.setVisible(true);
        lbl_capt2.setVisible(true);
        lbl_capt3.setVisible(true);
        lbl_capt4.setVisible(true);
        lbl_capt5.setVisible(true);
        lbl_capt6.setVisible(true);
        lbl_capt7.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_nama = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txt_usia = new javax.swing.JTextField();
        txt_berat = new javax.swing.JTextField();
        txt_tinggi = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        combo_jk = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn_kembali = new javax.swing.JButton();
        btn_hitung = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        lbl_capt1 = new javax.swing.JLabel();
        lbl_captKategori = new javax.swing.JLabel();
        lbl_capt5 = new javax.swing.JLabel();
        lbl_capt2 = new javax.swing.JLabel();
        lbl_capt7 = new javax.swing.JLabel();
        lbl_captNama = new javax.swing.JLabel();
        lbl_capt4 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lbl_captBMI = new javax.swing.JLabel();
        lbl_capt3 = new javax.swing.JLabel();
        lbl_capt6 = new javax.swing.JLabel();
        minimize = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/Gambar/iconapp.png")).getImage());
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_nama.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel1.add(txt_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 430, 30));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("(CM)");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 80, 20));

        txt_usia.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel1.add(txt_usia, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 80, 30));

        txt_berat.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel1.add(txt_berat, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 80, 30));

        txt_tinggi.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel1.add(txt_tinggi, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 80, 30));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Jenis Kelamin");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, 130, 20));

        combo_jk.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        combo_jk.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PILIH", "LAKI - LAKI", "PEREMPUAN" }));
        jPanel1.add(combo_jk, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, 130, 30));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Nama Lengkap");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 90, 30));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("(Tahun)");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 80, 20));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("(KG)");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 80, 20));

        btn_kembali.setBackground(new java.awt.Color(70, 43, 212));
        btn_kembali.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_kembali.setForeground(new java.awt.Color(255, 255, 255));
        btn_kembali.setText("KEMBALI");
        btn_kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kembaliActionPerformed(evt);
            }
        });
        jPanel1.add(btn_kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, 130, 30));

        btn_hitung.setBackground(new java.awt.Color(43, 100, 212));
        btn_hitung.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_hitung.setForeground(new java.awt.Color(255, 255, 255));
        btn_hitung.setText("HITUNG BMI");
        btn_hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hitungActionPerformed(evt);
            }
        });
        jPanel1.add(btn_hitung, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 130, 30));

        btn_hapus.setBackground(new java.awt.Color(52, 141, 203));
        btn_hapus.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_hapus.setForeground(new java.awt.Color(255, 255, 255));
        btn_hapus.setText("HAPUS DATA");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });
        jPanel1.add(btn_hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 130, 30));

        lbl_capt1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbl_capt1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_capt1.setText("BERIKUT INI ADALAH HASIL PERHITUNGAN BMI ANDA");
        jPanel1.add(lbl_capt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 430, 40));

        lbl_captKategori.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jPanel1.add(lbl_captKategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 370, 170, 20));

        lbl_capt5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbl_capt5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_capt5.setText("Nilai BMI anda berada dalam kategori");
        jPanel1.add(lbl_capt5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 240, 20));

        lbl_capt2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbl_capt2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_capt2.setText("Halo..");
        jPanel1.add(lbl_capt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 50, 20));

        lbl_capt7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbl_capt7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_capt7.setText("Terima Kasih telah menggunakan Aplikasi SIKESDU");
        jPanel1.add(lbl_capt7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, 430, 20));

        lbl_captNama.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jPanel1.add(lbl_captNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 390, 20));

        lbl_capt4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbl_capt4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_capt4.setText("Nilai BMI anda adalah ");
        jPanel1.add(lbl_capt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 140, 20));

        jLabel13.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Usia");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 80, 20));

        jLabel14.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Berat Badan");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 80, 20));

        jLabel15.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Tinggi Badan");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 80, 20));

        lbl_captBMI.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jPanel1.add(lbl_captBMI, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, 40, 20));

        lbl_capt3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbl_capt3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_capt3.setText("Berdasarkan dari Informasi Berat Badan serta Tinggi Badan anda");
        jPanel1.add(lbl_capt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 430, 20));

        lbl_capt6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbl_capt6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_capt6.setText("Tetap Jaga Kesehatan dimanapun anda berada.");
        jPanel1.add(lbl_capt6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, 430, 20));

        minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/icon-minimize.png"))); // NOI18N
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
        });
        jPanel1.add(minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, -10, 30, 30));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Design_BMIFrame.jpg"))); // NOI18N
        jPanel1.add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 500));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kembaliActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Welcome_Frame kembali = new Welcome_Frame();
        kembali.setVisible(true);
    }//GEN-LAST:event_btn_kembaliActionPerformed

    private void btn_hitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hitungActionPerformed
        // TODO add your handling code here:
        cekInput();
    }//GEN-LAST:event_btn_hitungActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        // TODO add your handling code here:
        kosong();
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        // TODO add your handling code here:
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_minimizeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BMI_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BMI_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BMI_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BMI_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BMI_Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_hitung;
    private javax.swing.JButton btn_kembali;
    private javax.swing.JComboBox<String> combo_jk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_capt1;
    private javax.swing.JLabel lbl_capt2;
    private javax.swing.JLabel lbl_capt3;
    private javax.swing.JLabel lbl_capt4;
    private javax.swing.JLabel lbl_capt5;
    private javax.swing.JLabel lbl_capt6;
    private javax.swing.JLabel lbl_capt7;
    private javax.swing.JLabel lbl_captBMI;
    private javax.swing.JLabel lbl_captKategori;
    private javax.swing.JLabel lbl_captNama;
    private javax.swing.JLabel minimize;
    private javax.swing.JTextField txt_berat;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_tinggi;
    private javax.swing.JTextField txt_usia;
    // End of variables declaration//GEN-END:variables
}
