package Kode;
import javax.swing.JOptionPane;

/**
 *
 * @author SIKESDU Developer
 */
public class DashboardKepala_Frame extends javax.swing.JFrame {

    public DashboardKepala_Frame() {
        initComponents();
        tampilUser();
    }
    
    DataKhusus DBKepala = new DataKhusus();
    
    private void tampilUser(){
        txt_nama.setText(DBKepala.get_nama()+" (@"+DBKepala.get_id()+")");
        txt_jabatan.setText(DBKepala.get_jabatan());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_nama = new javax.swing.JLabel();
        btn_akun = new javax.swing.JLabel();
        txt_jabatan = new javax.swing.JLabel();
        btn_logout = new javax.swing.JLabel();
        btn_laporan = new javax.swing.JLabel();
        btn_user = new javax.swing.JLabel();
        minimize = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/Gambar/iconapp.png")).getImage());
        setUndecorated(true);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_nama.setFont(new java.awt.Font("Malgun Gothic", 1, 20)); // NOI18N
        txt_nama.setForeground(new java.awt.Color(255, 255, 255));
        txt_nama.setText("Nama Kepala Posyandu");
        jPanel1.add(txt_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 730, 40));

        btn_akun.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_akunMouseClicked(evt);
            }
        });
        jPanel1.add(btn_akun, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, 90, 30));

        txt_jabatan.setFont(new java.awt.Font("Malgun Gothic", 1, 20)); // NOI18N
        txt_jabatan.setForeground(new java.awt.Color(255, 255, 255));
        txt_jabatan.setText("Kepala Posyandu");
        jPanel1.add(txt_jabatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 127, 190, 40));

        btn_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_logoutMouseClicked(evt);
            }
        });
        jPanel1.add(btn_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 10, 60, 20));

        btn_laporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_laporanMouseClicked(evt);
            }
        });
        jPanel1.add(btn_laporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 270, 240, 140));

        btn_user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_userMouseClicked(evt);
            }
        });
        jPanel1.add(btn_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 240, 140));

        minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/icon-minimize.png"))); // NOI18N
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
        });
        jPanel1.add(minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, -10, 30, 30));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Design_DashboardKepala.jpg"))); // NOI18N
        jPanel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_userMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_userMouseClicked
        this.dispose();
        ManajemenUser_Frame user = new ManajemenUser_Frame();
        user.setVisible(true); 
    }//GEN-LAST:event_btn_userMouseClicked

    private void btn_laporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_laporanMouseClicked
        this.dispose();
        PilihanLaporan_Frame laporan = new PilihanLaporan_Frame();
        laporan.setVisible(true);
    }//GEN-LAST:event_btn_laporanMouseClicked

    private void btn_akunMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_akunMouseClicked
        this.dispose();
        Profile_Frame profil = new Profile_Frame();
        profil.setVisible(true); 
    }//GEN-LAST:event_btn_akunMouseClicked

    private void btn_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_logoutMouseClicked
        String[] opsi = {"YA" , "TIDAK"};
        int jawab = JOptionPane.showOptionDialog(this, 
                "Apakah anda yakin akan Logout?" , 
                "Logout User", 
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE, null, opsi, opsi[1]);
        
        if (jawab == JOptionPane.YES_OPTION){
            DBKepala.set_idPegawai("");
            DBKepala.set_nama("");
            DBKepala.set_jabatan("");
            System.out.println("ID = "+DBKepala.get_id());
            System.out.println("Nama = "+DBKepala.get_nama());
            this.dispose();
            Login_Frame login = new Login_Frame();
            login.setVisible(true);
        }
    }//GEN-LAST:event_btn_logoutMouseClicked

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        // TODO add your handling code here:
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_minimizeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardKepala_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardKepala_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardKepala_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardKepala_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardKepala_Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel btn_akun;
    private javax.swing.JLabel btn_laporan;
    private javax.swing.JLabel btn_logout;
    private javax.swing.JLabel btn_user;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel minimize;
    private javax.swing.JLabel txt_jabatan;
    private static javax.swing.JLabel txt_nama;
    // End of variables declaration//GEN-END:variables
}
