package Kode;
import javax.swing.JOptionPane;

/**
 *
 * @author SIKESDU Developer
 */
public class DashboardBidan_Frame extends javax.swing.JFrame {

    public DashboardBidan_Frame() {
        initComponents();
        tampilUser();
    }
    
    DataKhusus DBBidan = new DataKhusus();
    Pilihan_Frame pilihan = new Pilihan_Frame();
    
    private void tampilUser(){
        txt_nama.setText(DBBidan.get_nama()+" (@"+DBBidan.get_id()+")");
        txt_jabatan.setText(DBBidan.get_jabatan());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_jabatan = new javax.swing.JLabel();
        txt_nama = new javax.swing.JLabel();
        btn_imunisasi = new javax.swing.JLabel();
        btn_masterImunisasi = new javax.swing.JLabel();
        btn_pendataan = new javax.swing.JLabel();
        btn_perkembangan = new javax.swing.JLabel();
        btn_edit = new javax.swing.JLabel();
        btn_logout = new javax.swing.JLabel();
        minimize = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/Gambar/iconapp.png")).getImage());
        setUndecorated(true);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_jabatan.setFont(new java.awt.Font("Malgun Gothic", 1, 20)); // NOI18N
        txt_jabatan.setForeground(new java.awt.Color(255, 255, 255));
        txt_jabatan.setText("Bidan");
        jPanel1.add(txt_jabatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 190, 50));

        txt_nama.setFont(new java.awt.Font("Malgun Gothic", 1, 20)); // NOI18N
        txt_nama.setForeground(new java.awt.Color(255, 255, 255));
        txt_nama.setText("Nama Bidan");
        jPanel1.add(txt_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 740, 40));

        btn_imunisasi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_imunisasiMouseClicked(evt);
            }
        });
        jPanel1.add(btn_imunisasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, 170, 120));

        btn_masterImunisasi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_masterImunisasiMouseClicked(evt);
            }
        });
        jPanel1.add(btn_masterImunisasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 170, 120));

        btn_pendataan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_pendataanMouseClicked(evt);
            }
        });
        jPanel1.add(btn_pendataan, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 270, 170, 120));

        btn_perkembangan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_perkembanganMouseClicked(evt);
            }
        });
        jPanel1.add(btn_perkembangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 170, 120));

        btn_edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_editMouseClicked(evt);
            }
        });
        jPanel1.add(btn_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, 90, 20));

        btn_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_logoutMouseClicked(evt);
            }
        });
        jPanel1.add(btn_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 10, 60, 20));

        minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/icon-minimize.png"))); // NOI18N
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
        });
        jPanel1.add(minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, -10, 30, 30));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Design_DashboardBidan.jpg"))); // NOI18N
        jPanel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_logoutMouseClicked
        String[] opsi = {"YA" , "TIDAK"};
        int jawab = JOptionPane.showOptionDialog(this, 
                "Apakah anda yakin akan Logout?" , 
                "Logout User", 
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE, null, opsi, opsi[1]);
        
        if (jawab == JOptionPane.YES_OPTION){
            DBBidan.set_idPegawai("");
            DBBidan.set_nama("");
            DBBidan.set_jabatan("");
            System.out.println("ID = "+DBBidan.get_id());
            System.out.println("Nama = "+DBBidan.get_nama());
            this.dispose();
            Login_Frame login = new Login_Frame();
            login.setVisible(true);
        }
    }//GEN-LAST:event_btn_logoutMouseClicked

    private void btn_editMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editMouseClicked
        this.dispose();
        Profile_Frame profil = new Profile_Frame();
        profil.setVisible(true); 
    }//GEN-LAST:event_btn_editMouseClicked

    private void btn_perkembanganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_perkembanganMouseClicked
        // TODO add your handling code here:
        this.dispose();
        pilihan.set_kategori("Perkembangan");
        pilihan.lbl_kategori.setText("Perkembangan");
        pilihan.setVisible(true);
    }//GEN-LAST:event_btn_perkembanganMouseClicked

    private void btn_pendataanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pendataanMouseClicked
        // TODO add your handling code here:
        this.dispose();
        pilihan.set_kategori("Pendataan");
        pilihan.lbl_kategori.setText("Pendataan");
        pilihan.setVisible(true);
    }//GEN-LAST:event_btn_pendataanMouseClicked

    private void btn_imunisasiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_imunisasiMouseClicked
        // TODO add your handling code here:
        this.dispose();
        Imunisasi_Frame imunBalita = new Imunisasi_Frame();
        imunBalita.setVisible(true);
    }//GEN-LAST:event_btn_imunisasiMouseClicked

    private void btn_masterImunisasiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_masterImunisasiMouseClicked
        // TODO add your handling code here:
        this.dispose();
        DataImunisasi_Frame dataimunisasi = new DataImunisasi_Frame();
        dataimunisasi.setVisible(true);
    }//GEN-LAST:event_btn_masterImunisasiMouseClicked

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        // TODO add your handling code here:
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_minimizeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardBidan_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardBidan_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardBidan_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardBidan_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardBidan_Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel btn_edit;
    private javax.swing.JLabel btn_imunisasi;
    private javax.swing.JLabel btn_logout;
    private javax.swing.JLabel btn_masterImunisasi;
    private javax.swing.JLabel btn_pendataan;
    private javax.swing.JLabel btn_perkembangan;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel minimize;
    private javax.swing.JLabel txt_jabatan;
    private javax.swing.JLabel txt_nama;
    // End of variables declaration//GEN-END:variables
}
