package Kode;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.awt.event.KeyEvent;
import java.util.regex.Pattern;

/**
 *
 * @author SIKESDU Developer
 */
public class Login_Frame extends javax.swing.JFrame {
        
    public Login_Frame() {
        initComponents();
    }
    
    DataKhusus login = new DataKhusus();
    String sql;
    
    private void cekLogin(){
        try{
            sql = "SELECT * FROM `user` WHERE "
                + "id_pegawai='"+txt_username.getText()+"' "
                + "and password=MD5('"+password.getText()+"')";
            java.sql.Connection con = (Connection)login.sambungDB();
            java.sql.PreparedStatement ps = con.prepareStatement(sql);
            java.sql.ResultSet r = ps.executeQuery(sql);
            if(r.next()){
                JOptionPane.showMessageDialog(this, 
                        "Login Berhasil! \nAKUN : "+r.getString("jabatan").toUpperCase() , 
                         "Informasi Login" ,
                     JOptionPane.INFORMATION_MESSAGE);
                login.set_idPegawai(r.getString("id_pegawai"));
                login.set_nama(r.getString("nama_lengkap"));
                login.set_jabatan(r.getString("jabatan"));
                this.dispose();
                if(r.getString("jabatan").equalsIgnoreCase("Kepala Posyandu")){
                    DashboardKepala_Frame kepala = new DashboardKepala_Frame();
                    kepala.setVisible(true);
                }else if(r.getString("jabatan").equalsIgnoreCase("Bidan Posyandu")){
                    DashboardBidan_Frame bidan = new DashboardBidan_Frame();
                    bidan.setVisible(true);
                }else if(r.getString("jabatan").equalsIgnoreCase("Kader Posyandu")){
                    DashboardKader_Frame kader = new DashboardKader_Frame();
                    kader.setVisible(true);
                }
                System.out.println("ID = "+login.get_id());
                System.out.println("Nama = "+login.get_nama());
            }else{
                JOptionPane.showMessageDialog(this, 
                            "Maaf Login GAGAL \nUsername atau Password anda Salah" , 
                            "Informasi Login" , 
                            JOptionPane.INFORMATION_MESSAGE);
            }
            
        }catch(SQLException e){
            System.out.println("Gagal Login \n"+e);
            System.out.println(sql);
        }
    }
    
    private void sanitasiUsername(){
        if(txt_username.getText().equals("") || password.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Seluruh Kolom Harus Di Isi!");
        }else{
            if(Pattern.matches("\\w*", txt_username.getText())){
                //Inputan Benar  
                cekLogin();
            }else{
                //Inputan Salah
                JOptionPane.showMessageDialog(this, 
                    "USERNAME HANYA BERISI ANGKA DAN HURUF!" , 
                    "PERINGATAN!!!", 
                    JOptionPane.WARNING_MESSAGE);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_username = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        btn_login = new javax.swing.JButton();
        btn_home = new javax.swing.JButton();
        minimize = new javax.swing.JLabel();
        lbl_loginkartu = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/Gambar/iconapp.png")).getImage());
        setUndecorated(true);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_username.setBackground(new java.awt.Color(255, 244, 244));
        txt_username.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        txt_username.setBorder(null);
        txt_username.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_usernameKeyPressed(evt);
            }
        });
        jPanel1.add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 160, 220, 40));

        password.setBackground(new java.awt.Color(255, 244, 244));
        password.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        password.setBorder(null);
        password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordKeyPressed(evt);
            }
        });
        jPanel1.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 250, 210, 40));

        btn_login.setFont(new java.awt.Font("Malgun Gothic", 1, 12)); // NOI18N
        btn_login.setText("LOGIN");
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });
        jPanel1.add(btn_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 350, 140, 40));

        btn_home.setFont(new java.awt.Font("Malgun Gothic", 1, 12)); // NOI18N
        btn_home.setText("HOME");
        btn_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_homeActionPerformed(evt);
            }
        });
        jPanel1.add(btn_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 350, 140, 40));

        minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/icon-minimize.png"))); // NOI18N
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
        });
        jPanel1.add(minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, -10, 30, 30));

        lbl_loginkartu.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        lbl_loginkartu.setForeground(new java.awt.Color(255, 255, 255));
        lbl_loginkartu.setText("Login Dengan Kartu?");
        lbl_loginkartu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_loginkartuMouseClicked(evt);
            }
        });
        jPanel1.add(lbl_loginkartu, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 450, -1, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Design_Login.png"))); // NOI18N
        jPanel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        sanitasiUsername();
    }//GEN-LAST:event_btn_loginActionPerformed

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        // TODO add your handling code here:
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_minimizeMouseClicked

    private void btn_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_homeActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Welcome_Frame welcome = new Welcome_Frame();
        welcome.setVisible(true);
    }//GEN-LAST:event_btn_homeActionPerformed

    private void txt_usernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_usernameKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            password.requestFocus();
        }
    }//GEN-LAST:event_txt_usernameKeyPressed

    private void passwordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            sanitasiUsername();
        }
    }//GEN-LAST:event_passwordKeyPressed

    private void lbl_loginkartuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_loginkartuMouseClicked
        // TODO add your handling code here:
        this.dispose();
        RFID_Frame login = new RFID_Frame();
        login.setVisible(true);
    }//GEN-LAST:event_lbl_loginkartuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton btn_home;
    private javax.swing.JButton btn_login;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_loginkartu;
    private javax.swing.JLabel minimize;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
