package Kode;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author SIKESDU Developer
 */
public class PilihanLaporan_Frame extends javax.swing.JFrame {

    public PilihanLaporan_Frame() {
        initComponents();
        reset();
    }
    
    DataKhusus khusus = new DataKhusus();
    Connection con = (Connection)khusus.sambungDB();
    
    String formatTGL = "yyyy-MM-dd";
    SimpleDateFormat fm = new SimpleDateFormat(formatTGL);
    String sql, tanggalawal, tanggalakhir, reportpath = "";
    
    private void cetakLaporan(){
        try{
            JasperReport jr = JasperCompileManager.compileReport(reportpath);
            HashMap parameter = new HashMap();
            parameter.put("tgl_awal", tanggalawal);
            parameter.put("tgl_akhir", tanggalakhir);
            JasperPrint jp = JasperFillManager.fillReport(jr, parameter, con);
            JasperViewer.viewReport(jp, false);
            reset();
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }
    
    private void reset(){
        tanggal_awal.setDate(null);
        tanggal_akhir.setDate(null);
        combo_jenis.setSelectedIndex(0);
        reportpath = "";
        tanggalawal = "";
        tanggalakhir = "";
        sql = "";
    }
    
    private void cekDataBumil(){
        try{
            sql = "SELECT COUNT(*) AS jumlah FROM `perkembangan_ibuhamil` "
                + "INNER JOIN `data_ibuhamil` ON perkembangan_ibuhamil.nik_ibuhamil = "
                + "data_ibuhamil.nik_ibuhamil WHERE tgl_periksa "
                + "BETWEEN '"+tanggalawal+"' and '"+tanggalakhir+"';";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            if(rs.next()){
                if(rs.getString("jumlah").equals("0")){
                    JOptionPane.showMessageDialog(this, 
                    "Maaf Data Kosong! \nPastikan Seluruh Kolom Terisi dengan Benar" , 
                    "Informasi Cetak Laporan" , 
                    JOptionPane.INFORMATION_MESSAGE);
                }else{
                    reportpath = "src\\Kode\\ReportBumil.jrxml";
                    cetakLaporan();
                }
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    private void cekDataBalita(){
        try{
            sql = "SELECT COUNT(*) as jumlah FROM `perkembangan_balita` "
                + "INNER JOIN `data_balita` ON perkembangan_balita.id_balita = "
                + "data_balita.id_balita WHERE tgl_periksa "
                + "BETWEEN '"+tanggalawal+"' and '"+tanggalakhir+"';";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            if(rs.next()){
                if(rs.getString("jumlah").equals("0")){
                    JOptionPane.showMessageDialog(this, 
                    "Maaf Data Kosong! \nPastikan Seluruh Kolom Terisi dengan Benar" , 
                    "Informasi Cetak Laporan" , 
                    JOptionPane.INFORMATION_MESSAGE);
                }else{
                    reportpath = "src\\Kode\\ReportBalita.jrxml";
                    cetakLaporan();
                }
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_cetak = new javax.swing.JButton();
        tanggal_akhir = new com.toedter.calendar.JDateChooser();
        tanggal_awal = new com.toedter.calendar.JDateChooser();
        btn_kembali = new javax.swing.JButton();
        btn_batal = new javax.swing.JButton();
        combo_jenis = new javax.swing.JComboBox<>();
        Header = new javax.swing.JLabel();
        Judul = new javax.swing.JLabel();
        Judul1 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/Gambar/iconapp.png")).getImage());
        setUndecorated(true);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_cetak.setBackground(new java.awt.Color(41, 132, 179));
        btn_cetak.setFont(new java.awt.Font("Malgun Gothic", 1, 12)); // NOI18N
        btn_cetak.setForeground(new java.awt.Color(255, 255, 255));
        btn_cetak.setText("Cetak Laporan");
        btn_cetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cetakActionPerformed(evt);
            }
        });
        jPanel1.add(btn_cetak, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 350, 30));

        tanggal_akhir.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N
        jPanel1.add(tanggal_akhir, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 170, 30));

        tanggal_awal.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N
        jPanel1.add(tanggal_awal, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 170, 30));

        btn_kembali.setBackground(new java.awt.Color(41, 132, 179));
        btn_kembali.setFont(new java.awt.Font("Malgun Gothic", 1, 12)); // NOI18N
        btn_kembali.setForeground(new java.awt.Color(255, 255, 255));
        btn_kembali.setText("Kembali");
        btn_kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kembaliActionPerformed(evt);
            }
        });
        jPanel1.add(btn_kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 170, 30));

        btn_batal.setBackground(new java.awt.Color(41, 132, 179));
        btn_batal.setFont(new java.awt.Font("Malgun Gothic", 1, 12)); // NOI18N
        btn_batal.setForeground(new java.awt.Color(255, 255, 255));
        btn_batal.setText("Batal");
        btn_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batalActionPerformed(evt);
            }
        });
        jPanel1.add(btn_batal, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 170, 30));

        combo_jenis.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N
        combo_jenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PILIH", "Perkembangan Ibu Hamil", "Perkembangan Balita" }));
        jPanel1.add(combo_jenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 350, 30));

        Header.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        Header.setForeground(new java.awt.Color(255, 255, 255));
        Header.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Header.setText("Cetak Laporan Perkembangan");
        jPanel1.add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 430, -1));

        Judul.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        Judul.setText("Tanggal Akhir");
        jPanel1.add(Judul, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 120, 30));

        Judul1.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        Judul1.setText("Tanggal Awal");
        jPanel1.add(Judul1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 100, 30));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Design_Pilihan_laporan.jpg"))); // NOI18N
        jPanel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 250));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cetakActionPerformed
        // TODO add your handling code here:
        if(tanggal_awal.getDate()==null || tanggal_akhir.getDate()==null || combo_jenis.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(this, 
            "Seluruh Kolom Harus Terisi!!!" , 
            "Informasi Cetak Laporan" , 
            JOptionPane.INFORMATION_MESSAGE);
        }else{
            tanggalawal = String.valueOf(fm.format(tanggal_awal.getDate()));
            tanggalakhir = String.valueOf(fm.format(tanggal_akhir.getDate()));
            if(combo_jenis.getSelectedItem().equals("Perkembangan Ibu Hamil")){
                cekDataBumil();
            }else if(combo_jenis.getSelectedItem().equals("Perkembangan Balita")){
                cekDataBalita();
            }
        }
    }//GEN-LAST:event_btn_cetakActionPerformed

    private void btn_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batalActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_btn_batalActionPerformed

    private void btn_kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kembaliActionPerformed
        // TODO add your handling code here:
        this.dispose();
        if(khusus.get_jabatan().equalsIgnoreCase("Kepala Posyandu")){
            DashboardKepala_Frame dbkepala = new DashboardKepala_Frame();
            dbkepala.setVisible(true);
        }else if(khusus.get_jabatan().equalsIgnoreCase("Bidan Posyandu")){
            DashboardBidan_Frame dbbidan= new DashboardBidan_Frame();
            dbbidan.setVisible(true);
        }else if(khusus.get_jabatan().equalsIgnoreCase("Kader Posyandu")){
            DashboardKader_Frame dbkader= new DashboardKader_Frame();
            dbkader.setVisible(true);
        }
    }//GEN-LAST:event_btn_kembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PilihanLaporan_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PilihanLaporan_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PilihanLaporan_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PilihanLaporan_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PilihanLaporan_Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Header;
    private javax.swing.JLabel Judul;
    private javax.swing.JLabel Judul1;
    private javax.swing.JLabel background;
    private javax.swing.JButton btn_batal;
    private javax.swing.JButton btn_cetak;
    private javax.swing.JButton btn_kembali;
    private javax.swing.JComboBox<String> combo_jenis;
    private javax.swing.JPanel jPanel1;
    private com.toedter.calendar.JDateChooser tanggal_akhir;
    private com.toedter.calendar.JDateChooser tanggal_awal;
    // End of variables declaration//GEN-END:variables
}
