package Kode;

/**
 *
 * @author SIKESDU Developer
 */
public class Pilihan_Frame extends javax.swing.JFrame {
    private String kategori;

    public Pilihan_Frame() {
        initComponents();
    }
    
    protected void set_kategori(String kategori){
        this.kategori = kategori;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanel = new javax.swing.JPanel();
        lbl_balita = new javax.swing.JLabel();
        lbl_bumil = new javax.swing.JLabel();
        lbl_kategori = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/Gambar/iconapp.png")).getImage());
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpanel.setPreferredSize(new java.awt.Dimension(450, 250));
        jpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_balita.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_balitaMouseClicked(evt);
            }
        });
        jpanel.add(lbl_balita, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 160, 200));

        lbl_bumil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_bumilMouseClicked(evt);
            }
        });
        jpanel.add(lbl_bumil, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 160, 210));

        lbl_kategori.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        lbl_kategori.setForeground(new java.awt.Color(255, 255, 255));
        lbl_kategori.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jpanel.add(lbl_kategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 16, 420, 30));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Design_Pilihan.jpg"))); // NOI18N
        jpanel.add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 250));

        getContentPane().add(jpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_bumilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_bumilMouseClicked
        // TODO add your handling code here:
        this.dispose();
        if(kategori.equals("Perkembangan")){
            PkBumil_Frame pkbumil = new PkBumil_Frame();
            kategori = "";
            pkbumil.setVisible(true);
        }else if(kategori.equals("Pendataan")){
            DataBumil_Frame dtbumil = new DataBumil_Frame();
            kategori = "";
            dtbumil.setVisible(true);
        }
    }//GEN-LAST:event_lbl_bumilMouseClicked

    private void lbl_balitaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_balitaMouseClicked
        // TODO add your handling code here:
        this.dispose();
        if(kategori.equals("Perkembangan")){
            PkBalita_Frame pkbalita = new PkBalita_Frame();
            kategori = "";
            pkbalita.setVisible(true);
        }else if(kategori.equals("Pendataan")){
            DataBalita_Frame dtbalita = new DataBalita_Frame();
            kategori = "";
            dtbalita.setVisible(true);
        }
    }//GEN-LAST:event_lbl_balitaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pilihan_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pilihan_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pilihan_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pilihan_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pilihan_Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JPanel jpanel;
    private javax.swing.JLabel lbl_balita;
    private javax.swing.JLabel lbl_bumil;
    protected javax.swing.JLabel lbl_kategori;
    // End of variables declaration//GEN-END:variables
}
