package Kode;

import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author SIKESDU Developer
 */
public class Profile_Frame extends javax.swing.JFrame {

    public Profile_Frame() {
        initComponents();
        reset();
    }
    
    DataKhusus profil = new DataKhusus();
    String ambil_id;
    
    private void reset(){
        btn_ubahPassword.setEnabled(false);
        btn_batal.setEnabled(false);
        Password_lama.setText("");
        Password_baru.setText("");
        ambil_id = "";
        tampilUser();
    }
    
    private void tampilUser(){
        try{
            String sql = "SELECT * FROM `user` WHERE "
                       + "id_pegawai='"+profil.get_id()+"'; ";
            java.sql.Connection con = (Connection)profil.sambungDB();
            java.sql.PreparedStatement ps = con.prepareStatement(sql);
            java.sql.ResultSet r = ps.executeQuery(sql);
            if(r.next()){
                txt_idPegawai.setText(profil.get_id());
                txt_idPegawai.setEditable(false);
                txt_nama.setText(r.getString("nama_lengkap"));
                txt_nama.setEditable(false);
                txt_tlp.setText(r.getString("telpon"));
                txt_tlp.setEditable(false);
            }
        }catch(SQLException e){
            System.out.println("Error \n"+e);
        }
    }
    
    private void UpdateDataAkun(){
        try{
            String sql = "UPDATE `user` SET "
                                + "`nama_lengkap` = '"+txt_nama.getText()+"', "
                                + "`telpon` = '"+txt_tlp.getText()+"' "
                                + "WHERE `user`.`id_pegawai` = '"+ambil_id+"';";
            java.sql.Connection con = (Connection)profil.sambungDB();
            java.sql.PreparedStatement pst = con.prepareStatement(sql);
            pst.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, 
                "Akun Berhasil Diperbarui \nAnda Akan Logout!", 
                "Perbarui Akun", 
                JOptionPane.INFORMATION_MESSAGE);
            profil.set_idPegawai("");
            profil.set_nama("");
            profil.set_jabatan("");
            System.out.println("ID = "+profil.get_id());
            System.out.println("Nama = "+profil.get_nama());
            this.dispose();
            Login_Frame login = new Login_Frame();
            login.setVisible(true);
        
        }catch(SQLException e){
            System.out.println("Error \n"+e);
        }
    }
    
    private void cekSandiLama(){
        try{
            String sql = "SELECT * FROM `user` WHERE "
                       + "id_pegawai='"+profil.get_id()+"'"
                       + "AND password=MD5('"+Password_lama.getText()+"');";
            java.sql.Connection con = (Connection)profil.sambungDB();
            java.sql.PreparedStatement ps = con.prepareStatement(sql);
            java.sql.ResultSet r = ps.executeQuery(sql);
            if(r.next()){
                ubahSandiBaru();
            }else{
                JOptionPane.showMessageDialog(this, 
                                    "PERMINTAAN DITOLAK!!! \nPassword Lama Anda Salah" , 
                                    "Perbarui Password" , 
                                    JOptionPane.WARNING_MESSAGE);
            }
        }catch(Exception e){
            System.out.println("Error \n"+e);
        }
    }
    
    private void ubahSandiBaru(){
        try{
            String sql = "UPDATE `user` SET "
                                + "`password` = MD5('"+Password_baru.getText()+"') "
                                + "WHERE `user`.`id_pegawai` = '"+profil.get_id()+"';";
            java.sql.Connection con = (Connection)profil.sambungDB();
            java.sql.PreparedStatement pst = con.prepareStatement(sql);
            pst.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, 
                "Password Anda Berhasil Diubah \nAnda Akan Logout!", 
                "Ubah Password", 
                JOptionPane.INFORMATION_MESSAGE);
            profil.set_idPegawai("");
            profil.set_nama("");
            profil.set_jabatan("");
            System.out.println("ID = "+profil.get_id());
            System.out.println("Nama = "+profil.get_nama());
            this.dispose();
            Login_Frame login = new Login_Frame();
            login.setVisible(true);
            
        }catch(SQLException e){
            System.out.println("Error \n"+e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_ubahPassword = new javax.swing.JButton();
        btn_batal = new javax.swing.JButton();
        btn_editAkun = new javax.swing.JButton();
        btn_ubahData = new javax.swing.JButton();
        txt_idPegawai = new javax.swing.JTextField();
        txt_nama = new javax.swing.JTextField();
        txt_tlp = new javax.swing.JTextField();
        btn_kembali = new javax.swing.JLabel();
        Password_baru = new javax.swing.JPasswordField();
        Password_lama = new javax.swing.JPasswordField();
        check_tampilsandi = new javax.swing.JCheckBox();
        minimize = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/Gambar/iconapp.png")).getImage());
        setUndecorated(true);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_ubahPassword.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_ubahPassword.setText("Perbarui Password");
        btn_ubahPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ubahPasswordActionPerformed(evt);
            }
        });
        jPanel1.add(btn_ubahPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 390, 150, 40));

        btn_batal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_batal.setText("Batal");
        btn_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batalActionPerformed(evt);
            }
        });
        jPanel1.add(btn_batal, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 390, 150, 40));

        btn_editAkun.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_editAkun.setText("Ubah");
        btn_editAkun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editAkunActionPerformed(evt);
            }
        });
        jPanel1.add(btn_editAkun, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, 150, 40));

        btn_ubahData.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_ubahData.setText("Simpan Perubahan");
        btn_ubahData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ubahDataActionPerformed(evt);
            }
        });
        jPanel1.add(btn_ubahData, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, 150, 40));

        txt_idPegawai.setEditable(false);
        txt_idPegawai.setBackground(new java.awt.Color(204, 204, 204));
        txt_idPegawai.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_idPegawai.setText("ID_Pegawai");
        txt_idPegawai.setBorder(null);
        jPanel1.add(txt_idPegawai, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 210, 40));

        txt_nama.setEditable(false);
        txt_nama.setBackground(new java.awt.Color(204, 204, 204));
        txt_nama.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_nama.setText("Nama Pegawai");
        txt_nama.setBorder(null);
        jPanel1.add(txt_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 210, 40));

        txt_tlp.setEditable(false);
        txt_tlp.setBackground(new java.awt.Color(204, 204, 204));
        txt_tlp.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_tlp.setText("08xxxxxxxxxx");
        txt_tlp.setBorder(null);
        jPanel1.add(txt_tlp, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 210, 40));

        btn_kembali.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        btn_kembali.setForeground(new java.awt.Color(255, 255, 255));
        btn_kembali.setText("Kembali");
        btn_kembali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_kembaliMouseClicked(evt);
            }
        });
        jPanel1.add(btn_kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 10, -1, -1));

        Password_baru.setBackground(new java.awt.Color(204, 204, 204));
        Password_baru.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Password_baru.setBorder(null);
        Password_baru.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Password_baruKeyTyped(evt);
            }
        });
        jPanel1.add(Password_baru, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 240, 180, 40));

        Password_lama.setBackground(new java.awt.Color(204, 204, 204));
        Password_lama.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Password_lama.setBorder(null);
        Password_lama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Password_lamaKeyTyped(evt);
            }
        });
        jPanel1.add(Password_lama, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 170, 180, 40));

        check_tampilsandi.setBackground(new java.awt.Color(1, 92, 146));
        check_tampilsandi.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        check_tampilsandi.setForeground(new java.awt.Color(255, 255, 255));
        check_tampilsandi.setText("Tampilkan Password");
        check_tampilsandi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_tampilsandiActionPerformed(evt);
            }
        });
        jPanel1.add(check_tampilsandi, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 300, 150, -1));

        minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/icon-minimize.png"))); // NOI18N
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
        });
        jPanel1.add(minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, -10, 30, 30));

        Background.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Design_Profile.jpg"))); // NOI18N
        jPanel1.add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batalActionPerformed
        // TODO add your handling code here:
        String[] opsi = {"YA" , "TIDAK"};
        int jawab = JOptionPane.showOptionDialog(this, 
                "Perubahan Tidak Akan Disimpan?" , 
                "Batalkan Perubahan", 
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE, null, opsi, opsi[1]);
        
        if (jawab == JOptionPane.YES_OPTION){
            reset();
        }
    }//GEN-LAST:event_btn_batalActionPerformed

    private void btn_ubahDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ubahDataActionPerformed
        // TODO add your handling code here:
        if(txt_nama.getText().equals("") || txt_tlp.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Seluruh kolom harus di isi!");
        }else{
            String[] opsi = {"YA" , "TIDAK"};
            int jawab = JOptionPane.showOptionDialog(this, 
                    "Apakah Anda Yakin Akan \nMemperbarui Data Akun?" , 
                    "Perbarui Akun", 
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE, null, opsi, opsi[1]);

            if (jawab == JOptionPane.YES_OPTION){
                UpdateDataAkun();
            }
        }
    }//GEN-LAST:event_btn_ubahDataActionPerformed

    private void btn_ubahPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ubahPasswordActionPerformed
        // TODO add your handling code here:
        if(Password_lama.getText().equals("") || Password_baru.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Harap Isi Kolom Password Lama dan Password Baru!");
        }else{
            cekSandiLama();
        }
    }//GEN-LAST:event_btn_ubahPasswordActionPerformed

    private void btn_kembaliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_kembaliMouseClicked
        this.dispose();
        if(profil.get_jabatan().equalsIgnoreCase("Kepala Posyandu")){
           DashboardKepala_Frame dbkepala = new DashboardKepala_Frame();
           dbkepala.setVisible(true);
        }else if(profil.get_jabatan().equalsIgnoreCase("Bidan Posyandu")){
           DashboardBidan_Frame dbbidan= new DashboardBidan_Frame();
           dbbidan.setVisible(true);
        }else if(profil.get_jabatan().equalsIgnoreCase("Kader Posyandu")){
           DashboardKader_Frame dbkader= new DashboardKader_Frame();
           dbkader.setVisible(true);
        }
    }//GEN-LAST:event_btn_kembaliMouseClicked

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        // TODO add your handling code here:
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_minimizeMouseClicked

    private void check_tampilsandiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_tampilsandiActionPerformed
        // TODO add your handling code here:
        if(check_tampilsandi.isSelected()){
            Password_baru.setEchoChar((char)0);
            Password_lama.setEchoChar((char)0);
        } else {
            Password_baru.setEchoChar('•');
            Password_lama.setEchoChar('•');
        }
    }//GEN-LAST:event_check_tampilsandiActionPerformed

    private void btn_editAkunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editAkunActionPerformed
        // TODO add your handling code here:
        txt_nama.setEditable(true);
        txt_tlp.setEditable(true);
        ambil_id = txt_idPegawai.getText();
        btn_batal.setEnabled(true);
    }//GEN-LAST:event_btn_editAkunActionPerformed

    private void Password_lamaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Password_lamaKeyTyped
        // TODO add your handling code here:
        btn_batal.setEnabled(true);
        btn_ubahPassword.setEnabled(true);
    }//GEN-LAST:event_Password_lamaKeyTyped

    private void Password_baruKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Password_baruKeyTyped
        // TODO add your handling code here:
        btn_batal.setEnabled(true);
        btn_ubahPassword.setEnabled(true);
    }//GEN-LAST:event_Password_baruKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Profile_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Profile_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Profile_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Profile_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Profile_Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JPasswordField Password_baru;
    private javax.swing.JPasswordField Password_lama;
    private javax.swing.JButton btn_batal;
    private javax.swing.JButton btn_editAkun;
    private javax.swing.JLabel btn_kembali;
    private javax.swing.JButton btn_ubahData;
    private javax.swing.JButton btn_ubahPassword;
    private javax.swing.JCheckBox check_tampilsandi;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel minimize;
    private javax.swing.JTextField txt_idPegawai;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_tlp;
    // End of variables declaration//GEN-END:variables
}
